// Generated by CoffeeScript 1.6.3
var App,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App = (function() {
  function App() {
    this.onLoad = __bind(this.onLoad, this);
    this.canvas = document.getElementById("canvas");
    this.ctx = canvas.getContext("2d");
    this.img1 = this.loadImage('images/demo-1.jpg', this.onLoad);
    this.img2 = this.loadImage('images/layer-1.png', this.onLoad);
    this.imagesLoaded = 0;
  }

  App.prototype.onLoad = function() {
    this.imagesLoaded += 1;
    if (this.imagesLoaded === 2) {
      this.ctx.drawImage(this.img1, 0, 0);
      this.ctx.globalAlpha = 0.5;
      return this.ctx.drawImage(this.img2, 0, 0);
    }
  };

  App.prototype.loadImage = function(src, onload) {
    var img;
    img = new Image();
    img.onload = onload;
    img.src = src;
    return img;
  };

  return App;

})();

$(function() {
  var app;
  return app = new App();
});
